### ISSUE TITLE
Grade Group vs. Maven GroupId

### ISSUE THREAD

**Issue by AustinLMayes** [sk89q/Intake#8]
In the readme and in your maven repository the groupId for this project is `com.sk89q`, in the current grade build file, the group is set to `com.sk89q.intake`. This breaks the maven grade install task. It also appears that you are no longer uploading to your maven repo (I might be wrong). Is this intentional, or is it a simple error?

**Comment by sk89q** [comment]
The README says that it's `com.sk89q.intake` for 4.x. The Maven Repo has 4.x in both groups because 4.0 was being published to the old group (`com.sk89q`) for a while before it was changed to the new group.

http://maven.sk89q.com/repo/com/sk89q/intake/4.0-SNAPSHOT/
http://maven.sk89q.com/repo/com/sk89q/intake/intake/4.0-SNAPSHOT/

**Comment by AustinLMayes** [comment]
Oh didn't see that. Opps, my bad :)
